name: hotelyn
description: "Awesome Flutter project"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.1

  hotelyn_models:
    path: packages/hotelyn_models

  intl: 0.19.0
  json_annotation: ^4.8.1
  logger: ^2.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  flutter_lints: ">=2.0.0 <5.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  melos: ">=3.1.1 <7.0.0"
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ">=5.1.0 <7.0.0"

fonts:
  - family: DMSans
    fonts:
      - asset: assets/fonts/DMSans_18pt-Regular.ttf
        style: regular
      - asset: assets/fonts/DMSans_18pt-Medium.ttf
        style: medium
      - asset: assets/fonts/DMSans_18pt-Bold.ttf
        style: bold

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/hotelyn/
    - assets/images/onboarding/
    - assets/images/messages/
    - assets/icons/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
          weight: 700
